// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	model "github.com/CoolBitX-Technology/subscan/plugins/bond/model"
	mock "github.com/stretchr/testify/mock"
)

// BondDelivery is an autogenerated mock type for the BondDelivery type
type BondDelivery struct {
	mock.Mock
}

// BondList provides a mock function with given fields: page, row, address, status, locked
func (_m *BondDelivery) BondList(page int, row int, address string, status string, locked int) ([]model.Bond, error) {
	ret := _m.Called(page, row, address, status, locked)

	var r0 []model.Bond
	if rf, ok := ret.Get(0).(func(int, int, string, string, int) []model.Bond); ok {
		r0 = rf(page, row, address, status, locked)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Bond)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string, string, int) error); ok {
		r1 = rf(page, row, address, status, locked)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
